{% set version = "1.14.5" %}

package:
  name: gstreamer_and_plugins
  version: {{ version }}

source:
  - url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-{{ version }}.tar.xz
    sha256: e40888752883177e97b2d90cd68591f87ccd213dc0178ff721d80a4cdaad34b5
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-{{ version }}.tar.xz
    sha256: 7bfa9b329ea7f3c654fa1b2d43650bf2646598a5e3cb21f42c516b7e975d638e
    folder: plugins_base
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-{{ version }}.tar.xz
    sha256: 678221b3f0208b31b90df3ffa509857cc8bfc337f3f5073d195c5b365d616503
    folder: plugins_good
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-{{ version }}.tar.xz
    sha256: 44da47126349fde90aed6c5ed0915f3b43f1d8802cd827139eb15a1fff1c6ad2
    folder: plugins_bad
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-{{ version }}.tar.xz
    sha256: 3ed802727286f18a9331cfed6ee85d07744d87cf868baae976615441f4bee04b
    folder: plugins_ugly


build:
  number: 0
  skip: true  # [win]

outputs:
  - name: gstreamer
    script: install_gstreamer.sh
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gstreamer', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - bison
        - flex
        - m4
        - autoconf
        - automake
        - make
        - perl
        - x264
      host:
        - gobject-introspection
        - gettext                            # [osx]
        - pcre                               # [linux]
        - libffi                             # [linux]
        - glib
        - x264
        - xz
      run:
        - x264

    test:
      commands:
        - gst-inspect-1.0 --version
        - gst-launch-1.0  --version
        - gst-stats-1.0 --version
        - gst-typefind-1.0 --version
    about:
      summary: "Library for constructing graphs of media-handling components"
      description:
      doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/docs

  - name: gst-plugins-base
    script: install_base_plugins.sh
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gst-plugins-base', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - pkg-config
        - m4
        - autoconf
        - automake
        - make
        - perl
        - x264
      host:
        - {{ pin_subpackage('gstreamer') }}
        - gobject-introspection
        - glib
        - zlib
        - gettext                            # [osx]
        - libxcb                             # [linux]
        - pthread-stubs                      # [linux]
        - x264
        - xz
      run:
        - {{ pin_compatible('gstreamer') }}
        - x264

    test:
      commands:
        - test -f $PREFIX/lib/libgstallocators-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstapp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstaudio-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstfft-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstpbutils-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstriff-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtsp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstsdp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgsttag-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstvideo-1.0${SHLIB_EXT}

    about:
        summary: "GStreamer Base Plug-ins"
        description: |
          GStreamer Base Plug-ins is a well-groomed and well-maintained collection of
          GStreamer plug-ins and elements, spanning the range of possible types of
          elements one would want to write for GStreamer.
        doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs

  - name: gst-plugins-good
    script: install_good_plugins.sh
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gst-plugins-good', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - pkg-config
        - m4
        - autoconf
        - automake
        - make
        - perl
        - x264
      host:
        - {{ pin_subpackage('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
        - gobject-introspection
        - glib
        - zlib
        - gettext                            # [osx]
        - libxcb                             # [linux]
        - pthread-stubs                      # [linux]
        - x264
        - xz
      run:
        - {{ pin_compatible('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
        - x264

    test:
      commands:
        - test -f $PREFIX/lib/libgstallocators-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstapp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstaudio-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstfft-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstpbutils-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstriff-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtsp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstsdp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgsttag-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstvideo-1.0${SHLIB_EXT}

    about:
      summary: "GStreamer Base Plug-ins"
      description: |
        GStreamer Base Plug-ins is a well-groomed and well-maintained collection of
        GStreamer plug-ins and elements, spanning the range of possible types of
        elements one would want to write for GStreamer.
      doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs

  - name: gst-plugins-bad
    script: install_bad_plugins.sh
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gst-plugins-bad', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - pkg-config
        - m4
        - autoconf
        - automake
        - make
        - perl
        - x264
      host:
        - {{ pin_subpackage('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
        - gobject-introspection
        - glib
        - zlib
        - gettext                            # [osx]
        - libxcb                             # [linux]
        - pthread-stubs                      # [linux]
        - x264
        - xz
      run:
        - {{ pin_compatible('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
        - x264

    test:
      commands:
        - test -f $PREFIX/lib/libgstallocators-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstapp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstaudio-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstfft-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstpbutils-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstriff-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtsp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstsdp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgsttag-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstvideo-1.0${SHLIB_EXT}

    about:
      summary: "GStreamer Base Plug-ins"
      description: |
        GStreamer Base Plug-ins is a well-groomed and well-maintained collection of
        GStreamer plug-ins and elements, spanning the range of possible types of
        elements one would want to write for GStreamer.
      doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs

  - name: gst-plugins-ugly
    script: install_ugly_plugins.sh
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gst-plugins-ugly', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - x264
        - pkg-config
        - m4
        - autoconf
        - automake
        - make
        - perl
      host:
        - {{ pin_subpackage('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
        - gobject-introspection
        - glib
        - zlib
        - gettext                            # [osx]
        - libxcb                             # [linux]
        - pthread-stubs                      # [linux]
        - x264
        - xz
      run:
        - {{ pin_compatible('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
        - x264

    test:
      commands:
        - test -f $PREFIX/lib/libgstallocators-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstapp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstaudio-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstfft-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstpbutils-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstriff-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtsp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstsdp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgsttag-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstvideo-1.0${SHLIB_EXT}

    about:
      summary: "GStreamer Base Plug-ins"
      description: |
        GStreamer Base Plug-ins is a well-groomed and well-maintained collection of
        GStreamer plug-ins and elements, spanning the range of possible types of
        elements one would want to write for GStreamer.
      doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs


about:
  home: http://gstreamer.freedesktop.org/
  summary: "Library for constructing graphs of media-handling components"
  license: LGPL-2.0
  doc_url: https://gstreamer.freedesktop.org/documentation/
  dev_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - msarahan
